# Training Configurations for English-to-Amharic Seq2Seq NMT

data:
  huggingface_dataset: "michsethowusu/english-amharic_sentence-pairs_mt560"
  min_freq: 5
  train_split: 0.80
  val_split: 0.10
  test_split: 0.10

training:
  batch_size: 64
  learning_rate: 0.001
  clip: 1.0
  teacher_forcing_ratio: 0.5
  seed: 42
  num_test_batches: 100

optimizer:
  type: "Adam"
  lr: 0.001

loss:
  type: "CrossEntropyLoss"
  ignore_index: 0
